name: Deploy to Digital Ocean
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          composer install
          npm install

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
          config: |
            Host *
              StrictHostKeyChecking no
          name: id_rsa

      - name: Set SSH key permissions
        run: chmod 600 ~/.ssh/id_rsa

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          rsync -avz --delete \
            --exclude='.env' \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.gitignore' \
            --exclude='.gitattributes' \
            --exclude='.vscode' \
            --exclude='scss' \
            --exclude='package-lock.json' \
            --exclude='package.json' \
            --exclude='composer.lock' \
            --exclude='jsconfig.json' \
            --exclude='netlify.toml' \
            ./  ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:/var/www/html/jsarray/

      - name: Run post-deployment commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} '
            cd /var/www/html/jsarray && 
            sudo chown -R www-data:www-data . &&
            sudo chmod -R 755 . &&
            sudo systemctl restart apache2
          '
